### ISSUE TITLE
SSL reencrypt

### ISSUE THREAD

**Issue by speedfl** [openshift-s2i/s2i-wildfly#152]
How is it possible to put ssl certifcate to be able to configure the route with reencrypt instead of edge?

**Comment by bparees** [comment]
you mean how do you configure wildfly to serve using a cert you provide?  

include the cert in your source repo and include appropriate wildfly configuration in your source repo.

**Comment by speedfl** [comment]
Hello,

Sorry for the delay but I have 100 of things to finished before focusing on it.

I already created  wildfly.keystore and add it in my config of standalone.
On local it works perfectly. When I enter in my pod and curl:

```https://localhost:8443/ping```

I am getting a success response. Meaning that inside the pod everything is working.

However the problem is that this image just exposes port 8080. 
No port 8443 (which is default https for wildfly) and no port 443 (default https)

So when I create my route I get warning on openshift console: 

```
oc create route reencrypt my-route \
--service=my-service \
--port=8443 \
--cert=/etc/letsencrypt/live/api.mydomain.com/fullchain.pem \
--key=/etc/letsencrypt/live/api.mydomain.com/privkey.pem \
--hostname=api.mydomain.com \
--insecure-policy=Redirect -n my-project
```
"The service does not expose 8443"

Same for 443

So I tried to modify the service by hands by adding the port 8443 but I was unable to make it work (with both 443 and 8443)

The problem with:

```
oc create route edge my-route \
--service=my-service \
--port=8080\
--cert=/etc/letsencrypt/live/api.mydomain.com/fullchain.pem \
--key=/etc/letsencrypt/live/api.mydomain.com/privkey.pem \
--hostname=api.mydomain.com \
--insecure-policy=Redirect -n my-project
```
The edge means that terminaison is done at the router. 
Is that it is acceptable if all the machines are located in the same datacenter (which is my case for the moment)

However if router is not located in the same datacenter as the node on which the pod is deployed the data will transit in clear. 

With a reencrypt we are sure that data are always crypted. Because the termination will be done at router but it will reencrypt the data to call the pod


Maybe you have ideas?

**Comment by bparees** [comment]
just create a service that exposes the container's port 8443 and then point the route to that service.

it doesn't matter if the image declares that it exposes the port, you can still setup a service pointing to any port you want in a container.

**Comment by speedfl** [comment]
When I go in Edit Yaml for my service I get:

```
spec:
  clusterIP: IP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
```

If I look at the route I can see my routes.
If route2 is like route1 (point to 8080 with Edge) it is working. However pointing to 8443 or 443 with reencrypt do not work. In fact I am getting:

503 service not available

![route](https://user-images.githubusercontent.com/23298035/35195221-a89d0f8e-fec0-11e7-9a02-8dfe71e52193.png)

**Comment by bparees** [comment]
> To have a service pointing to 8443 we need to have as well the pod which exposes the port 8443.

You can do that.  Add the port to the pod spec.  My point is it doesn't matter what ports the *image* declares.  (it only matters in the sense that oc new-app will attempt to do some logic based on what ports the image claims to declare).

If you want to send traffic to port 8443 in your container, then declare port 8443 in your container definition.

**Comment by speedfl** [comment]
Thanks a lot for your answer. I will try to do that and I will let you know :)

**Comment by bparees** [comment]
@speedfl i'm hoping this worked out for you, if not please comment back and we can reopen.

**Comment by speedfl** [comment]
Hello Sorry fir the long notice but we had lot of things to do and I finally was able to replug my brain on this topic.

So basically I modified my DC to expose port 8443. It directly rolled out and deploy a new pod.

So if I go to my pod now I have: 

```
spec:
  containers:
    - image: >-
        docker-registry.default.svc:5000/test/my-server@sha256:59ecf351172dce989f8b37801cce32b231540d040b937b844db5c61fc0542ae3
      imagePullPolicy: Always
      name: my-server
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
```
Then I updated the service to redirect to port 8443:

```
spec:
  clusterIP: 172.30.72.168
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
```

So if from my infra node I ping it:

```
curl --insecure -I https://172.30.72.168:8443/common/ping?API_KEY=<API_KEY>
```

Then I get status 200. Then I created a route

```
oc create route reencrypt my-route \
--service=my-service \
--port=8443\
--cert=/etc/letsencrypt/live/api.mydomain.com/fullchain.pem \
--key=/etc/letsencrypt/live/api.mydomain.com/privkey.pem \
--hostname=api.mydomain.com \
--insecure-policy=Redirect -n my-project
```

But when I try to access it I have the same error. Application is not available...
